defaults:
  - config: default
  - optimization_config: default
  - data_config: default
  - wandb_logger_kwargs: default
  - trainer_config: default

experiment_dir:
  value: ???
task_df_name:
  value: ???
load_from_model_dir:
  value: "skip"
pretrained_weights_fp:
  value: "skip"
