defaults:
  - config: default
  - optimization_config: default
  - data_config: default
  - pretraining_metrics_config: default
  - final_validation_metrics_config: default
  - wandb_logger_kwargs: default
  - trainer_config: default


experiment_dir: 
  value: '/mnt/fast_drive/experiment/predeath_procedure_new_ext'
data_config:
  #train_subset_seed: 1
  train_subset_size: 
    value: 0.2
  save_dir: 
    value: '/mnt/data_volume/apdc/esgpt_data_test/predeath5yr_procedure_new_ext'


optimization_config:
  max_epochs: 
    value: 10
  num_dataloader_workers: 
    value: 2

do_overwrite:
  value: False

do_final_validation_on_metrics:
  value: True
