seed: 123
stratified: True
n_splits: 5
test_size: null
windows: 
  - six_months
  - one_year
  - two_year
tasks:
  - length_of_stay
  - episode_count
  - cost
#result_fout_format: '{window}_results_binary_{high}_strat_debug.csv'
#result_fout_format: '{task}_results_binary_{high}_embed_test_gbt.csv'
#result_fout_format: '{task}_results_binary_{high}_embed_test_40k.csv'
#result_fout_format: '{task}_results_binary_heldout_20k.csv'
result_fout_format: '{task}_results_binary_heldout_diagnosis.csv'
run_label: 'diagnosis_dup'
label_path_nt: 'H:/aws_mnt/study1_files/'
#label_path_linux: '/mnt/data_volume/apdc/study1/preprocessed/tasks'
label_path_linux: '/mnt/fast_drive/h_drive/study1_files'
